### ISSUE TITLE
Auth Token or API key?

### ISSUE THREAD

**Issue by jotka** [netsage-project/grafana-dashboard-manager#34]
hi
The authentication with Auth Token doesn't seem to work, even when created with Admin permission.
Is it the API key I need to create or am I missing something here? 
Thanks a lot!

**Comment by safaci2000** [comment]
Everything I've been using has been with the API Token and has been working fine.  One thing to note though the User API requires Basic Auth since tokens aren't supported.  Can you tell me a bit more about your environment? Or show me what your config looks like (minus the sensitive info)

**Comment by jotka** [comment]
i have the Azure Active Directory integrated for users to login. I also need to interact with Grafana using API, so I've created the API key. As soon I run the grafana-dashboard-manager with this key in the config, I get 403 for getting organizations...

**Comment by jotka** [comment]
that's my importer.yaml:

```
context_name: spyglass
    contexts:
      spyglass:
        dashboards_output: /tmp
        url: http://grafana.spyglass.svc.cluster.local:3000
        token: [removed]
        organization: Main Org
        watched:
          - General
          - Other
```


and this is what I get when executing gdg dashboards list:

```
root@grafana-sync-5955cfbb9-hq6kf:/# gdg dashboards list
time="2021-07-17T04:51:51Z" level=fatal msg="Error getting organizations: HTTP error 403: returns {\"message\":\"Permission denied\"}"
```

<img width="1071" alt="api key" src="https://user-images.githubusercontent.com/2701356/126026153-b56ed1dc-9c2e-47ab-b89b-d71956f762be.png">
